all: check

check: Compile Run_Check

install: Run_Samba

remove: Run_RemoveSamba

Compile:
	chmod +x check_file.sh
	chmod +x Samba.sh
	chmod +x re-Samba.sh
Run_Check:
	./check_file.sh
Run_Samba:
	./Samba.sh
Run_RemoveSamba:
	./re-Samba.sh
