all: check

check: Compile Run_Check

install: Run_Git

tool: Run_Tool

remove: Run_RemoveGit

Compile:
	chmod +x check_file.sh
	chmod +x Git.sh
	chmod +x GitTool.sh
Run_Check:
	./check_file.sh
Run_Git:
	./Git.sh
Run_RemoveGit:
	./re-Git.sh
Run_Tool:
	./GitTool.sh
